apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# MongoDB Community Operator
# Install from: https://github.com/mongodb/mongodb-kubernetes-operator

namespace: mongodb-operator

resources:
  # - https://github.com/mongodb/mongodb-kubernetes-operator/releases/download/v0.8.0/mongodb-kubernetes-operator.yaml
  - operator-deployment.yaml





