apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eutlas-dev

resources:
  - ../../base/namespace.yaml

patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: eutlas-dev
    target:
      kind: Namespace
      name: eutlas-system

commonLabels:
  environment: development



