apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - mongodb.yaml
  - redis.yaml
  - secrets.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
  - rbac.yaml


