apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eutlas-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - mongo.eutlas.eu
      secretName: eutlas-prod-tls
  rules:
    - host: mongo.eutlas.eu
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: eutlas-backend
                port:
                  number: 4000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eutlas-frontend
                port:
                  number: 3000
