{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eutlas.serviceAccountName" . }}
  labels:
    {{- include "eutlas.labels" . | nindent 4 }}
{{- end }}


